### ISSUE TITLE
Create Session Creation Page

### ISSUE THREAD

**Issue by ClaudiaDietrichLev** [ClaudiaSollinger/journal-your-heart#1]
# TechTasks:

- [x] Design  Main Layout - #4 
- [ ] Design Select-Fields - #8 
- [x] Design Main Button - #6 
- [x] Function Select-Fields
- [x] Function Count
- [x] Function output How many questions
- [ ] function Create Session (select random prompts from the session-type and same them in an session object and in localstorage

![image](https://user-images.githubusercontent.com/110988007/204126404-106f5f32-6278-4c09-957b-0fc1162dbe5d.png)
